### ISSUE TITLE
appimage hangs on startup

### ISSUE THREAD

**Issue by AgyarJanos** [eclipse-theia/theia-ide#358]
### Bug Description:
trying to start appimage. worked fine, then started hanging on 2 separate computers a couple of days ago. now works on one, not the other. 

### Steps to Reproduce:

1. start appimage
2. hangs.
3.

### Additional Information

- Operating System: arch linux
- Theia Version: 1.48.300
- output when running from console stops after "2024-04-29T12:39:10.551Z root INFO Deploy plugins list: 603.4 ms [Finished 1.104 s after backend start]"
- both systems systemctl --version systemd 255 (255.5-2-arch), uname -r 6.8.7-arch1-2
- just for fun, downgraded nonfunctional system to 6.6.29-1-lts kernel; no difference
- deleted .theia-ide folder; no difference
- no logs created; .theia-ide contains only empty localization-cache folder
- stopped working simulaneously on both machines; randomly started again on one of them--issue with updating process? my best guess.
- copied the appimage, downloaded again; no difference
- moved back to intellij for now {8'>
- upgraded arch this morning; possibly relevant to suddenly working system, but why would only one be affected?

**Comment by jfaltermeier** [comment]
Thanks for reporting. 

Besides the `.theia-ide` directory there is also `~/.config/Theia IDE/` which contains caches from electron/chromium. 
The logs for the updater are in `~/.config/Theia IDE/logs/main.log`

When it hangs, are you able to access the chrome debugging tools in the electron app via ctrl+alt+i ? Maybe there is something in the logs.

**Comment by marcdumais-work** [comment]
> poll([{fd=12, events=POLLIN}, {fd=13, events=POLLIN}, {fd=46, events=POLLIN}, {fd=47, events=POLLIN}], 4, 11) = 1 ([{fd=13, revents=POLLIN}])
> recvmsg(46, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)

Good observation, but I think these polling errors would probably be unrelated to the issue - IIRC they are the result of the app using polling file watchers, watching for the appearance of config files, in the workspace (under folders `.theia` and `.vscode`) and in the user's home folder, so that the app can react if any of these files appears. The files are tasks.json, config.json, launch.json and maybe more.

If you are using a pre-built AppImage, you may have more success with a self-built one, especially if your system is older (e.g. older glibc) vs the distro the pre-built one is built-on.
